(setq inferior-lisp-program "/usr/bin/sbcl")
;(setq inferior-lisp-program "~/ccl-dev/lx86cl64")
;(setq inferior-lisp-program "/usr/bin/clisp")
;(setq inferior-lisp-program "/usr/bin/ecl")
(sly)
;;;; (sly-connect "localhost" 4005)
